-- 1. Create Base/Lookup Tables First
CREATE TABLE public.children (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.children ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.children ADD CONSTRAINT children_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.children TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.children TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.children TO service_role;

CREATE TABLE public.ethnicities (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.ethnicities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ethnicities ADD CONSTRAINT ethnicity_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ethnicities TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ethnicities TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ethnicities TO service_role;

CREATE TABLE public.family_plans (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.family_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_plans ADD CONSTRAINT family_plans_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.family_plans TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.family_plans TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.family_plans TO service_role;

CREATE TABLE public.genders (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text, plural_name text);
ALTER TABLE public.genders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.genders ADD CONSTRAINT gender_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.genders TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.genders TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.genders TO service_role;

CREATE TABLE public.interaction_status (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, status text NOT NULL);
ALTER TABLE public.interaction_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interaction_status ADD CONSTRAINT interaction_status_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.interaction_status TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.interaction_status TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.interaction_status TO service_role;

CREATE TABLE public.pets (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.pets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pets ADD CONSTRAINT pets_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pets TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pets TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pets TO service_role;

CREATE TABLE public.prompts (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, question text);
ALTER TABLE public.prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts ADD CONSTRAINT prompts_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.prompts TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.prompts TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.prompts TO service_role;

CREATE TABLE public.pronouns (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.pronouns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pronouns ADD CONSTRAINT pronouns_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pronouns TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pronouns TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pronouns TO service_role;

CREATE TABLE public.sexualities (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.sexualities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sexualities ADD CONSTRAINT sexualities_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sexualities TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sexualities TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sexualities TO service_role;

CREATE TABLE public.zodiac_signs (id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, name text);
ALTER TABLE public.zodiac_signs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zodiac_signs ADD CONSTRAINT zodiac_signs_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.zodiac_signs TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.zodiac_signs TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.zodiac_signs TO service_role;


-- 2. Create Profiles Table (Which depends on children, family_plans, genders, sexualities, zodiac_signs)
CREATE TABLE public.profiles (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp without time zone DEFAULT now(), first_name text, last_name text, dob date, height_cm integer, longitude double precision, latitude double precision, neighbourhood text, children_id integer, family_plan_id integer, zodiac_sign_id integer, gender_id integer, sexuality_id integer, max_distance_km integer DEFAULT 160, min_age integer DEFAULT 20, max_age integer DEFAULT 100, phone text);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_phone_key UNIQUE (phone);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_children_id_fkey FOREIGN KEY (children_id) REFERENCES public.children(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_family_plan_id_fkey FOREIGN KEY (family_plan_id) REFERENCES public.family_plans(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES public.genders(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_sexuality_id_fkey FOREIGN KEY (sexuality_id) REFERENCES public.sexualities(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_zodiac_sign_id_fkey FOREIGN KEY (zodiac_sign_id) REFERENCES public.zodiac_signs(id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profiles TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profiles TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profiles TO service_role;


-- 3. Create Dependent Profile Tables & Profile Junction Tables
CREATE TABLE public.profile_answers (id uuid DEFAULT gen_random_uuid() NOT NULL, profile_id uuid NOT NULL, prompt_id integer NOT NULL, answer_text text NOT NULL, answer_order integer NOT NULL, is_active boolean NOT NULL, created_at timestamp without time zone DEFAULT now());
ALTER TABLE public.profile_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_answers ADD CONSTRAINT profile_answers_pkey PRIMARY KEY (id);
ALTER TABLE public.profile_answers ADD CONSTRAINT profile_answers_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_answers TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_answers TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_answers TO service_role;

CREATE TABLE public.profile_ethnicities (profile_id uuid NOT NULL, ethnicity_id integer NOT NULL);
ALTER TABLE public.profile_ethnicities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_ethnicities ADD CONSTRAINT profile_ethnicities_pkey PRIMARY KEY (profile_id, ethnicity_id);
ALTER TABLE public.profile_ethnicities ADD CONSTRAINT profile_ethnicities_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profile_ethnicities ADD CONSTRAINT profile_ethnicities_ethnicity_fkey FOREIGN KEY (ethnicity_id) REFERENCES public.ethnicities(id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_ethnicities TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_ethnicities TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_ethnicities TO service_role;

CREATE TABLE public.profile_gender_preferences (profile_id uuid NOT NULL, gender_id integer NOT NULL);
ALTER TABLE public.profile_gender_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_gender_preferences ADD CONSTRAINT profile_gender_preferences_pkey PRIMARY KEY (profile_id, gender_id);
ALTER TABLE public.profile_gender_preferences ADD CONSTRAINT profile_gender_preferences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profile_gender_preferences ADD CONSTRAINT profile_gender_preferences_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES public.genders(id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_gender_preferences TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_gender_preferences TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_gender_preferences TO service_role;

CREATE TABLE public.profile_pets (profile_id uuid NOT NULL, pet_id integer NOT NULL);
ALTER TABLE public.profile_pets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_pets ADD CONSTRAINT profile_pets_pkey PRIMARY KEY (profile_id, pet_id);
ALTER TABLE public.profile_pets ADD CONSTRAINT profile_pets_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profile_pets ADD CONSTRAINT profile_pets_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_pets TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_pets TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_pets TO service_role;

CREATE TABLE public.profile_photos (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, profile_id uuid NOT NULL, photo_url text NOT NULL, photo_order integer NOT NULL, is_active boolean NOT NULL);
ALTER TABLE public.profile_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_photos ADD CONSTRAINT profile_photos_pkey PRIMARY KEY (id);
ALTER TABLE public.profile_photos ADD CONSTRAINT profile_photos_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_photos TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_photos TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_photos TO service_role;

CREATE TABLE public.profile_pronouns (profile_id uuid NOT NULL, pronoun_id integer NOT NULL);
ALTER TABLE public.profile_pronouns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_pronouns ADD CONSTRAINT profile_pronouns_pkey PRIMARY KEY (profile_id, pronoun_id);
ALTER TABLE public.profile_pronouns ADD CONSTRAINT profile_pronouns_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.profile_pronouns ADD CONSTRAINT profile_pronouns_pronoun_id_fkey FOREIGN KEY (pronoun_id) REFERENCES public.pronouns(id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_pronouns TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_pronouns TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_pronouns TO service_role;


-- 4. Create Interactions Table Last (Depends on profiles, status, answers, and photos)
CREATE TABLE public.interactions (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp without time zone DEFAULT now() NOT NULL, updated_by uuid NOT NULL, actor_id uuid NOT NULL, target_id uuid NOT NULL, status_id integer NOT NULL, answer_id uuid NOT NULL, photo_id uuid NOT NULL);
ALTER TABLE public.interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interactions ADD CONSTRAINT interactions_pkey PRIMARY KEY (id);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.interaction_status(id);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.profile_answers(id);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_photo_id_fkey FOREIGN KEY (photo_id) REFERENCES public.profile_photos(id);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.profiles(id);
ALTER TABLE public.interactions ADD CONSTRAINT interactions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.interactions TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.interactions TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.interactions TO service_role;
